version: '3'

services:
  kirara-agent:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kirara-agent
    restart: unless-stopped
    ports:
      - "8443:8080"
    volumes:
      - ./config:/app/config
    environment:
      - PORT=8080
      - LOG_LEVEL=info

  deploy-server:
    image: nginx:alpine
    container_name: deploy-server
    restart: unless-stopped
    ports:
      - "8081:80"
    volumes:
      - ./deploy:/usr/share/nginx/html:ro
