version: '3'

services:
  kirara-agent:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kirara-agent
    restart: unless-stopped
    ports:
      - "3970:8080"  # 更换安全端口为 8888
    volumes:
      - ./config:/app/config
    environment:
      - PORT=8080
      - LOG_LEVEL=info
